import { useEffect, useRef } from "react";
import { Btn, Green } from "../components/ui";
import { scrollTo } from "../data/portfolio";
const ROLES = ["React Developer", "Frontend Engineer", "UI Builder"];
export function Home() {
  const roleRef = useRef(null); const state = useRef({ index: 0, chars: 0, deleting: false });
  useEffect(() => { let timer; const tick = () => { const current = ROLES[state.current.index]; if (!roleRef.current) return; state.current.chars += state.current.deleting ? -1 : 1; roleRef.current.textContent = current.slice(0, state.current.chars); if (state.current.chars === current.length) { state.current.deleting = true; timer = setTimeout(tick, 1800); return; } if (state.current.chars === 0) { state.current.deleting = false; state.current.index = (state.current.index + 1) % ROLES.length; } timer = setTimeout(tick, state.current.deleting ? 60 : 100); }; timer = setTimeout(tick, 400); return () => clearTimeout(timer); }, []);
  return <section id="home" style={{ minHeight:"100vh", display:"flex", alignItems:"center", padding:"80px 6% 60px", gap:"6%", overflow:"hidden" }}><div style={{ flex:1.2, zIndex:1 }}><p style={{ fontSize:13, letterSpacing:3, textTransform:"uppercase", color:"#059669", fontWeight:600, marginBottom:16 }}>— &nbsp; Hello, I'm</p><h1 style={{ fontFamily:"Syne,sans-serif", fontSize:"clamp(44px,6.5vw,78px)", fontWeight:800, lineHeight:1.05, marginBottom:16, color:"#0f172a" }}>Adhitya <Green>K</Green></h1><div style={{ display:"flex", alignItems:"center", gap:16, marginBottom:22, flexWrap:"wrap" }}><span style={{ fontFamily:"Syne,sans-serif", fontSize:"clamp(28px,4.5vw,54px)", fontWeight:800, color:"#059669" }}>WEB</span><span style={{ width:10, height:10, borderRadius:"50%", background:"#cbd5e1" }} /><span style={{ fontFamily:"Syne,sans-serif", fontSize:"clamp(28px,4.5vw,54px)", fontWeight:800, color:"#d97706" }}>Developer</span></div><div style={{ height:32, marginBottom:22, color:"#5b6b78", fontSize:17 }}>— <span ref={roleRef} /><span style={{ display:"inline-block", width:2, height:20, background:"#059669", animation:"blink 1s step-end infinite" }} /></div><p style={{ color:"#5b6b78", fontSize:15, lineHeight:1.85, maxWidth:480, marginBottom:38 }}>Self-taught Frontend Developer skilled in React, building and shipping real-world applications end to end. Currently gaining professional experience in a fast-paced tech environment while pursuing a full-time Frontend Developer role.</p><div style={{ display:"flex", gap:14, flexWrap:"wrap" }}><Btn primary onClick={() => scrollTo("projects")}>View My Work →</Btn><Btn onClick={() => scrollTo("contact")}>Contact Me</Btn></div><div style={{ display:"flex", gap:40, marginTop:50 }}><Stat value="4" label="Projects Built" /><Stat value="3" label="Live Demos" /><Stat value="1.5+" label="Yrs at TCS" /></div></div><div style={{ flex:.85, display:"flex", justifyContent:"center" }}><div style={{ position:"relative" }}><div style={{ width:"min(290px,38vw)", aspectRatio:"3/4", borderRadius:20, overflow:"hidden", border:"2px solid rgba(5,150,105,.16)", background:"linear-gradient(145deg,#ecfdf5,#d1fae5)", display:"flex", alignItems:"center", justifyContent:"center", boxShadow:"0 20px 50px rgba(15,23,42,.08)" }}><img src="/Photo.jpeg" alt="Adhitya K" style={{ width:"100%", height:"100%", objectFit:"cover" }} /></div><div style={{ position:"absolute", bottom:20, left:-20, background:"#059669", color:"#fff", fontSize:12, fontWeight:700, padding:"8px 18px", borderRadius:24 }}>⚛ React Dev</div></div></div></section>;
}
function Stat({ value, label }) { return <div><div style={{ fontFamily:"Syne,sans-serif", fontSize:34, fontWeight:800, color:"#059669", lineHeight:1 }}>{value}</div><div style={{ fontSize:11, color:"#8296a3", textTransform:"uppercase", letterSpacing:1.5, marginTop:4 }}>{label}</div></div>; }
